Threading and Plugin System Rewrite
Far-Beyond-Dev/Horizon-Community-Edition pull request #182
Opened 2024-11-06 06:43 UTC by tristanpoland

# Pull Request Summary: Threading and Plugin System Rewrite

## Overview
This PR introduces a major rewrite of the plugin system architecture with a focus on improved threading and state management.

## Key Changes

### Architecture Changes
- Complete rewrite of plugin API architecture
- Introduction of new plugin state management system
- Migration from `Mutex` to `RwLock` for improved concurrent access
- New threading model with parallel iterators using Rayon

### Plugin System
- Added plugin state tracking (ACTIVE, INACTIVE, CRASH)
- Improved plugin lifecycle management (load, unload, disable)
- New error handling for plugin crashes
- Introduced versioning system for plugins
- Added test infrastructure for plugin system

### Dependencies
- Updated core dependencies:
  - socketioxide -> 0.15.1
  - Added rayon for parallel processing
  - Removed several unused dependencies
  - Consolidated dependency versions

### Performance Optimizations
- Implemented parallel iterators for player data processing
- Improved concurrent access patterns using RwLock
- Better memory management in player state updates

## Breaking Changes
- Plugin API interface has changed significantly
- State management system requires plugin updates
- Threading model changes may require client adaptations

## Testing
- Added unit tests for plugin management
- New test cases for plugin states
- Error handling test coverage

## Migration Notes
Existing plugins will need to be updated to work with the new API structure and state management system.

2024-11-06 22:22 UTC, tristanpoland commented
This PR among other things will allow us to complete #173 and further integrate with other plugins and game engines over socketioxide

2024-11-07 16:17 UTC, tristanpoland commented
@Tuafo When you get the chance would you mind helping me on a PebbleVault plugin rework? it and a bunch of the other plugins will need to change how they work in order to work properly in the new API. Shouldn't take too long I think.

2024-11-07 19:42 UTC, tristanpoland commented
@haywoodspartan @Tuafo @WilliamAnimate Would you guys mind taking a look at how plugins are written on this branch (mainly the struct plugin defined in the horizon_plugin_api crate and implementing a different trait on the struct in each plugin (see /plugins/test_plugin))

I want to know if you guys think this is a solid way of doing function calls to plugins in a type-safe way. 

Thanks you guys ❤️

2024-11-07 19:54 UTC, tristanpoland commented on src/main.rs
> +                // (TODO: Change this to a per-thread instance of manager and
We will clear this up in the final revision of the API before we merge but after we get the all clear from reviewers

2024-11-07 19:59 UTC, WilliamAnimate commented
I'll take a look when i get back home; I'm in a class right now

2024-11-07 20:00 UTC, tristanpoland commented
> I'll take a look when i get back home; I'm in a class right now

Stay in school kids 😆
Talk to you when you are home then

2024-11-07 21:23 UTC, WilliamAnimate requested changes
I see the code

```rust
// Define the trait properly
pub trait Plugin_API {    
    fn thing(&self) -> String;
}

pub trait Plugin_Construct {
    // If you want default implementations, mark them with 'default'
    fn new(plugins: HashMap<&'static str, LoadedPlugin>, socket: SocketRef, players: Arc<RwLock<Vec<horizon_data_types::Player>>>) -> Plugin;
}
```

being repeated multiple times throughout different plugins. maybe put it into some crate, and reference it?

2024-11-07 21:28 UTC, CatTrim approved these changes

2024-11-07 22:35 UTC, tristanpoland commented
> I see the code
> 
> ```rust
> // Define the trait properly
> pub trait Plugin_API {    
>     fn thing(&self) -> String;
> }
> 
> pub trait Plugin_Construct {
>     // If you want default implementations, mark them with 'default'
>     fn new(plugins: HashMap<&'static str, LoadedPlugin>, socket: SocketRef, players: Arc<RwLock<Vec<horizon_data_types::Player>>>) -> Plugin;
> }
> ```
> 
> being repeated multiple times throughout different plugins. maybe put it into some crate, and reference it?

This is due to each plugin needing to impl its own API, these can be customized but in the case of the plugins we have it is not yet

2024-11-10 17:15 UTC, merged